apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: detg8047x-go-gitops
  description: This is GitOps manifest for detg8047x-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=detg8047x-go
    backstage.io/kubernetes-id: detg8047x-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-qe-jsmid/detg8047x-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:detg8047x-go
